// Generated by Wrangler by running `wrangler types`

interface Env {
	CACHE: KVNamespace;
	DATABASE_URL: string;
	JWT_SECRET: string;
	EMAIL_FROM: string;
	FRONTEND_URL: string;
	BREVO_API_KEY: string;
	MISTRAL_API_KEY: string;
	GOOGLE_CLIENT_ID: string;
	GOOGLE_CLIENT_SECRET: string;
	USER_CONNECTIONS: DurableObjectNamespace<import("./src/index").UserConnection>;
}
