/**
 * OtakuShelf — 100 Badge Definitions
 *
 * Each badge:
 *  id          — unique string key, used for deduplication
 *  title       — display name
 *  description — shown on the profile page
 *  icon        — emoji (no SVG/img needed yet)
 *  rarity      — 'common' | 'uncommon' | 'rare' | 'epic' | 'legendary'
 *  category    — grouping label for UI
 *  check(stats)— pure fn, returns true if earned. stats shape defined in badgeEngine.js
 */

const BADGES = [

  // ─────────────────────────────────────────────────────────────────
  // CATEGORY 1 — FIRST STEPS (5)
  // ─────────────────────────────────────────────────────────────────
  {
    id: 'first_step',
    title: 'First Step',
    description: 'Add your very first anime to any list',
    icon: '🌱',
    rarity: 'common',
    category: 'First Steps',
    check: (s) => s.totalAnime >= 1,
  },
  {
    id: 'first_complete',
    title: 'First Finish',
    description: 'Complete your very first anime',
    icon: '✅',
    rarity: 'common',
    category: 'First Steps',
    check: (s) => s.completed >= 1,
  },
  {
    id: 'first_drop',
    title: 'Dropped One',
    description: 'Drop your first anime',
    icon: '💔',
    rarity: 'common',
    category: 'First Steps',
    check: (s) => s.dropped >= 1,
  },
  {
    id: 'first_rating',
    title: 'Critic Awakened',
    description: 'Rate your very first anime',
    icon: '⭐',
    rarity: 'common',
    category: 'First Steps',
    check: (s) => s.ratedCount >= 1,
  },
  {
    id: 'well_rounded',
    title: 'Well Rounded',
    description: 'Have at least 1 anime in all 4 list categories',
    icon: '🎯',
    rarity: 'uncommon',
    category: 'First Steps',
    check: (s) => s.watching >= 1 && s.completed >= 1 && s.planned >= 1 && s.dropped >= 1,
  },

  // ─────────────────────────────────────────────────────────────────
  // CATEGORY 2 — ANIME COUNT MILESTONES (10)
  // ─────────────────────────────────────────────────────────────────
  {
    id: 'total_5',
    title: 'Just Starting',
    description: '5+ anime across all lists',
    icon: '🐣',
    rarity: 'common',
    category: 'Anime Count',
    check: (s) => s.totalAnime >= 5,
  },
  {
    id: 'total_10',
    title: 'Building Up',
    description: '10+ anime across all lists',
    icon: '📚',
    rarity: 'common',
    category: 'Anime Count',
    check: (s) => s.totalAnime >= 10,
  },
  {
    id: 'total_25',
    title: 'Dedicated Viewer',
    description: '25+ anime across all lists',
    icon: '🎬',
    rarity: 'common',
    category: 'Anime Count',
    check: (s) => s.totalAnime >= 25,
  },
  {
    id: 'total_50',
    title: 'Seasoned Watcher',
    description: '50+ anime across all lists',
    icon: '🌟',
    rarity: 'uncommon',
    category: 'Anime Count',
    check: (s) => s.totalAnime >= 50,
  },
  {
    id: 'total_100',
    title: 'Century Club',
    description: '100+ anime across all lists',
    icon: '💯',
    rarity: 'uncommon',
    category: 'Anime Count',
    check: (s) => s.totalAnime >= 100,
  },
  {
    id: 'total_250',
    title: 'Elite Otaku',
    description: '250+ anime across all lists',
    icon: '🔥',
    rarity: 'rare',
    category: 'Anime Count',
    check: (s) => s.totalAnime >= 250,
  },
  {
    id: 'total_500',
    title: 'Legendary',
    description: '500+ anime across all lists',
    icon: '🌌',
    rarity: 'rare',
    category: 'Anime Count',
    check: (s) => s.totalAnime >= 500,
  },
  {
    id: 'total_1000',
    title: 'Mythical',
    description: '1000+ anime across all lists',
    icon: '🪐',
    rarity: 'epic',
    category: 'Anime Count',
    check: (s) => s.totalAnime >= 1000,
  },
  {
    id: 'total_2000',
    title: 'Transcendent',
    description: '2000+ anime across all lists',
    icon: '⚡',
    rarity: 'legendary',
    category: 'Anime Count',
    check: (s) => s.totalAnime >= 2000,
  },
  {
    id: 'total_5000',
    title: 'Infinite',
    description: '5000+ anime across all lists',
    icon: '♾️',
    rarity: 'legendary',
    category: 'Anime Count',
    check: (s) => s.totalAnime >= 5000,
  },

  // ─────────────────────────────────────────────────────────────────
  // CATEGORY 3 — COMPLETIONIST (8)
  // ─────────────────────────────────────────────────────────────────
  {
    id: 'complete_5',
    title: 'Finisher',
    description: 'Complete 5 anime',
    icon: '🏅',
    rarity: 'common',
    category: 'Completionist',
    check: (s) => s.completed >= 5,
  },
  {
    id: 'complete_10',
    title: 'Serial Finisher',
    description: 'Complete 10 anime',
    icon: '🏆',
    rarity: 'common',
    category: 'Completionist',
    check: (s) => s.completed >= 10,
  },
  {
    id: 'complete_25',
    title: 'Completionist',
    description: 'Complete 25 anime',
    icon: '🥇',
    rarity: 'uncommon',
    category: 'Completionist',
    check: (s) => s.completed >= 25,
  },
  {
    id: 'complete_50',
    title: 'Master Finisher',
    description: 'Complete 50 anime',
    icon: '🎖️',
    rarity: 'uncommon',
    category: 'Completionist',
    check: (s) => s.completed >= 50,
  },
  {
    id: 'complete_100',
    title: 'Grand Completionist',
    description: 'Complete 100 anime',
    icon: '👑',
    rarity: 'rare',
    category: 'Completionist',
    check: (s) => s.completed >= 100,
  },
  {
    id: 'complete_250',
    title: 'Anime Scholar',
    description: 'Complete 250 anime',
    icon: '🌠',
    rarity: 'epic',
    category: 'Completionist',
    check: (s) => s.completed >= 250,
  },
  {
    id: 'complete_500',
    title: 'Half Thousand',
    description: 'Complete 500 anime',
    icon: '🔮',
    rarity: 'legendary',
    category: 'Completionist',
    check: (s) => s.completed >= 500,
  },
  {
    id: 'complete_1000',
    title: 'Millennium',
    description: 'Complete 1000 anime — are you even human?',
    icon: '🏯',
    rarity: 'legendary',
    category: 'Completionist',
    check: (s) => s.completed >= 1000,
  },

  // ─────────────────────────────────────────────────────────────────
  // CATEGORY 4 — EPISODE MILESTONES (10)
  // ─────────────────────────────────────────────────────────────────
  {
    id: 'episodes_50',
    title: 'Episode Starter',
    description: 'Watch 50+ total episodes',
    icon: '👀',
    rarity: 'common',
    category: 'Episode Milestones',
    check: (s) => s.totalEpisodes >= 50,
  },
  {
    id: 'episodes_100',
    title: 'Episode Enthusiast',
    description: 'Watch 100+ total episodes',
    icon: '📺',
    rarity: 'common',
    category: 'Episode Milestones',
    check: (s) => s.totalEpisodes >= 100,
  },
  {
    id: 'episodes_500',
    title: 'Marathon Runner',
    description: 'Watch 500+ total episodes',
    icon: '🏃',
    rarity: 'common',
    category: 'Episode Milestones',
    check: (s) => s.totalEpisodes >= 500,
  },
  {
    id: 'episodes_1000',
    title: 'Episode Master',
    description: 'Watch 1000+ total episodes',
    icon: '🎯',
    rarity: 'uncommon',
    category: 'Episode Milestones',
    check: (s) => s.totalEpisodes >= 1000,
  },
  {
    id: 'episodes_2500',
    title: 'Episode Train',
    description: 'Watch 2500+ total episodes',
    icon: '🚂',
    rarity: 'uncommon',
    category: 'Episode Milestones',
    check: (s) => s.totalEpisodes >= 2500,
  },
  {
    id: 'episodes_5000',
    title: 'Episode Warrior',
    description: 'Watch 5000+ total episodes',
    icon: '⚔️',
    rarity: 'rare',
    category: 'Episode Milestones',
    check: (s) => s.totalEpisodes >= 5000,
  },
  {
    id: 'episodes_10000',
    title: 'Episode Ocean',
    description: 'Watch 10,000+ total episodes',
    icon: '🌊',
    rarity: 'epic',
    category: 'Episode Milestones',
    check: (s) => s.totalEpisodes >= 10000,
  },
  {
    id: 'episodes_25000',
    title: 'Episode Volcano',
    description: 'Watch 25,000+ total episodes',
    icon: '🌋',
    rarity: 'epic',
    category: 'Episode Milestones',
    check: (s) => s.totalEpisodes >= 25000,
  },
  {
    id: 'episodes_50000',
    title: 'Episode World',
    description: 'Watch 50,000+ total episodes',
    icon: '🌍',
    rarity: 'legendary',
    category: 'Episode Milestones',
    check: (s) => s.totalEpisodes >= 50000,
  },
  {
    id: 'episodes_100000',
    title: 'Episode Universe',
    description: 'Watch 100,000+ total episodes — absolute legend',
    icon: '🌌',
    rarity: 'legendary',
    category: 'Episode Milestones',
    check: (s) => s.totalEpisodes >= 100000,
  },

  // ─────────────────────────────────────────────────────────────────
  // CATEGORY 5 — HOURS WATCHED (8)
  // Estimation: avg 24 min/episode → 1 ep ≈ 0.4 hours
  // ─────────────────────────────────────────────────────────────────
  {
    id: 'hours_24',
    title: 'Day Gone',
    description: 'Watch 24+ hours worth of anime',
    icon: '⏰',
    rarity: 'common',
    category: 'Hours Watched',
    check: (s) => s.hoursWatched >= 24,
  },
  {
    id: 'hours_100',
    title: 'Time Investor',
    description: 'Watch 100+ hours of anime',
    icon: '📅',
    rarity: 'common',
    category: 'Hours Watched',
    check: (s) => s.hoursWatched >= 100,
  },
  {
    id: 'hours_168',
    title: 'Week Gone',
    description: 'Watch a full week (168 hours) of anime',
    icon: '🗓️',
    rarity: 'uncommon',
    category: 'Hours Watched',
    check: (s) => s.hoursWatched >= 168,
  },
  {
    id: 'hours_500',
    title: 'Time Hoarder',
    description: 'Watch 500+ hours of anime',
    icon: '⌚',
    rarity: 'uncommon',
    category: 'Hours Watched',
    check: (s) => s.hoursWatched >= 500,
  },
  {
    id: 'hours_720',
    title: 'Month Gone',
    description: 'Watch a full month (720 hours) of anime',
    icon: '📆',
    rarity: 'rare',
    category: 'Hours Watched',
    check: (s) => s.hoursWatched >= 720,
  },
  {
    id: 'hours_2190',
    title: 'Quarter Year',
    description: 'Watch a full quarter year (2190 hours) of anime',
    icon: '📊',
    rarity: 'rare',
    category: 'Hours Watched',
    check: (s) => s.hoursWatched >= 2190,
  },
  {
    id: 'hours_4380',
    title: 'Half Year Devoted',
    description: 'Watch a half year (4380 hours) of anime',
    icon: '🧭',
    rarity: 'epic',
    category: 'Hours Watched',
    check: (s) => s.hoursWatched >= 4380,
  },
  {
    id: 'hours_8760',
    title: 'Full Year Otaku',
    description: 'Watch a full year (8760 hours) of anime — send help',
    icon: '🏔️',
    rarity: 'legendary',
    category: 'Hours Watched',
    check: (s) => s.hoursWatched >= 8760,
  },

  // ─────────────────────────────────────────────────────────────────
  // CATEGORY 6 — GENRE EXPLORER (19, one per AniList genre)
  // ─────────────────────────────────────────────────────────────────
  {
    id: 'genre_action',
    title: 'Action Hero',
    description: 'Watch at least 1 Action anime',
    icon: '⚡',
    rarity: 'common',
    category: 'Genre Explorer',
    check: (s) => (s.genreCounts['Action'] || 0) >= 1,
  },
  {
    id: 'genre_adventure',
    title: 'Adventure Seeker',
    description: 'Watch at least 1 Adventure anime',
    icon: '🗺️',
    rarity: 'common',
    category: 'Genre Explorer',
    check: (s) => (s.genreCounts['Adventure'] || 0) >= 1,
  },
  {
    id: 'genre_avant_garde',
    title: 'Avant Garde',
    description: 'Watch at least 1 Avant Garde anime',
    icon: '🎨',
    rarity: 'uncommon',
    category: 'Genre Explorer',
    check: (s) => (s.genreCounts['Avant Garde'] || 0) >= 1,
  },
  {
    id: 'genre_award_winning',
    title: 'Award Hunter',
    description: 'Watch at least 1 Award Winning anime',
    icon: '🏅',
    rarity: 'uncommon',
    category: 'Genre Explorer',
    check: (s) => (s.genreCounts['Award Winning'] || 0) >= 1,
  },
  {
    id: 'genre_boys_love',
    title: 'Boys Love Fan',
    description: 'Watch at least 1 Boys Love anime',
    icon: '💙',
    rarity: 'common',
    category: 'Genre Explorer',
    check: (s) => (s.genreCounts['Boys Love'] || 0) >= 1,
  },
  {
    id: 'genre_comedy',
    title: 'Comedy Lover',
    description: 'Watch at least 1 Comedy anime',
    icon: '😂',
    rarity: 'common',
    category: 'Genre Explorer',
    check: (s) => (s.genreCounts['Comedy'] || 0) >= 1,
  },
  {
    id: 'genre_drama',
    title: 'Drama Expert',
    description: 'Watch at least 1 Drama anime',
    icon: '😢',
    rarity: 'common',
    category: 'Genre Explorer',
    check: (s) => (s.genreCounts['Drama'] || 0) >= 1,
  },
  {
    id: 'genre_fantasy',
    title: 'Fantasy Fanatic',
    description: 'Watch at least 1 Fantasy anime',
    icon: '🧙',
    rarity: 'common',
    category: 'Genre Explorer',
    check: (s) => (s.genreCounts['Fantasy'] || 0) >= 1,
  },
  {
    id: 'genre_girls_love',
    title: 'Girls Love Fan',
    description: 'Watch at least 1 Girls Love anime',
    icon: '💗',
    rarity: 'common',
    category: 'Genre Explorer',
    check: (s) => (s.genreCounts['Girls Love'] || 0) >= 1,
  },
  {
    id: 'genre_gourmet',
    title: 'Gourmet Explorer',
    description: 'Watch at least 1 Gourmet anime',
    icon: '🍜',
    rarity: 'uncommon',
    category: 'Genre Explorer',
    check: (s) => (s.genreCounts['Gourmet'] || 0) >= 1,
  },
  {
    id: 'genre_horror',
    title: 'Horror Survivor',
    description: 'Watch at least 1 Horror anime',
    icon: '👻',
    rarity: 'common',
    category: 'Genre Explorer',
    check: (s) => (s.genreCounts['Horror'] || 0) >= 1,
  },
  {
    id: 'genre_mystery',
    title: 'Mystery Detective',
    description: 'Watch at least 1 Mystery anime',
    icon: '🔍',
    rarity: 'common',
    category: 'Genre Explorer',
    check: (s) => (s.genreCounts['Mystery'] || 0) >= 1,
  },
  {
    id: 'genre_romance',
    title: 'Romantic Heart',
    description: 'Watch at least 1 Romance anime',
    icon: '💕',
    rarity: 'common',
    category: 'Genre Explorer',
    check: (s) => (s.genreCounts['Romance'] || 0) >= 1,
  },
  {
    id: 'genre_sci_fi',
    title: 'Sci-Fi Explorer',
    description: 'Watch at least 1 Sci-Fi anime',
    icon: '🚀',
    rarity: 'common',
    category: 'Genre Explorer',
    check: (s) => (s.genreCounts['Sci-Fi'] || 0) >= 1,
  },
  {
    id: 'genre_slice_of_life',
    title: 'Slice of Life',
    description: 'Watch at least 1 Slice of Life anime',
    icon: '☕',
    rarity: 'common',
    category: 'Genre Explorer',
    check: (s) => (s.genreCounts['Slice of Life'] || 0) >= 1,
  },
  {
    id: 'genre_sports',
    title: 'Sports Fanatic',
    description: 'Watch at least 1 Sports anime',
    icon: '⚽',
    rarity: 'common',
    category: 'Genre Explorer',
    check: (s) => (s.genreCounts['Sports'] || 0) >= 1,
  },
  {
    id: 'genre_supernatural',
    title: 'Supernatural Believer',
    description: 'Watch at least 1 Supernatural anime',
    icon: '👁️',
    rarity: 'common',
    category: 'Genre Explorer',
    check: (s) => (s.genreCounts['Supernatural'] || 0) >= 1,
  },
  {
    id: 'genre_suspense',
    title: 'Suspense Seeker',
    description: 'Watch at least 1 Suspense anime',
    icon: '😰',
    rarity: 'common',
    category: 'Genre Explorer',
    check: (s) => (s.genreCounts['Suspense'] || 0) >= 1,
  },
  {
    id: 'genre_thriller',
    title: 'Thriller Fan',
    description: 'Watch at least 1 Thriller anime',
    icon: '🎭',
    rarity: 'common',
    category: 'Genre Explorer',
    check: (s) => (s.genreCounts['Thriller'] || 0) >= 1,
  },

  // ─────────────────────────────────────────────────────────────────
  // CATEGORY 7 — GENRE MASTER (5)
  // ─────────────────────────────────────────────────────────────────
  {
    id: 'genre_master_action',
    title: 'Action Master',
    description: 'Watch 10+ Action anime',
    icon: '💥',
    rarity: 'rare',
    category: 'Genre Master',
    check: (s) => (s.genreCounts['Action'] || 0) >= 10,
  },
  {
    id: 'genre_master_romance',
    title: 'Romance Master',
    description: 'Watch 10+ Romance anime',
    icon: '🌹',
    rarity: 'rare',
    category: 'Genre Master',
    check: (s) => (s.genreCounts['Romance'] || 0) >= 10,
  },
  {
    id: 'genre_master_fantasy',
    title: 'Fantasy Master',
    description: 'Watch 10+ Fantasy anime',
    icon: '🐉',
    rarity: 'rare',
    category: 'Genre Master',
    check: (s) => (s.genreCounts['Fantasy'] || 0) >= 10,
  },
  {
    id: 'genre_master_comedy',
    title: 'Comedy Master',
    description: 'Watch 10+ Comedy anime',
    icon: '🎤',
    rarity: 'rare',
    category: 'Genre Master',
    check: (s) => (s.genreCounts['Comedy'] || 0) >= 10,
  },
  {
    id: 'genre_master_mystery',
    title: 'Mystery Master',
    description: 'Watch 10+ Mystery anime',
    icon: '🕵️',
    rarity: 'rare',
    category: 'Genre Master',
    check: (s) => (s.genreCounts['Mystery'] || 0) >= 10,
  },

  // ─────────────────────────────────────────────────────────────────
  // CATEGORY 8 — RATING BADGES (7)
  // ─────────────────────────────────────────────────────────────────
  {
    id: 'rated_10',
    title: 'Budding Critic',
    description: 'Rate 10 anime',
    icon: '📝',
    rarity: 'common',
    category: 'Rating',
    check: (s) => s.ratedCount >= 10,
  },
  {
    id: 'rated_25',
    title: 'Active Critic',
    description: 'Rate 25 anime',
    icon: '🖊️',
    rarity: 'uncommon',
    category: 'Rating',
    check: (s) => s.ratedCount >= 25,
  },
  {
    id: 'rated_50',
    title: 'Star Collector',
    description: 'Rate 50 anime',
    icon: '📖',
    rarity: 'uncommon',
    category: 'Rating',
    check: (s) => s.ratedCount >= 50,
  },
  {
    id: 'rated_100',
    title: 'Master Critic',
    description: 'Rate 100 anime',
    icon: '🧐',
    rarity: 'rare',
    category: 'Rating',
    check: (s) => s.ratedCount >= 100,
  },
  {
    id: 'perfectionist',
    title: 'Perfectionist',
    description: 'Give a perfect 5/5 rating to 10 or more anime',
    icon: '💎',
    rarity: 'rare',
    category: 'Rating',
    check: (s) => s.perfectRatings >= 10,
  },
  {
    id: 'high_standards',
    title: 'High Standards',
    description: 'Maintain an average rating above 4.0 across 20+ rated anime',
    icon: '📐',
    rarity: 'uncommon',
    category: 'Rating',
    check: (s) => s.ratedCount >= 20 && s.avgRating > 4.0,
  },
  {
    id: 'harsh_critic',
    title: 'Harsh Critic',
    description: 'Give 1/5 to 5 or more anime — you have standards',
    icon: '🔪',
    rarity: 'uncommon',
    category: 'Rating',
    check: (s) => s.lowestRatings >= 5,
  },

  // ─────────────────────────────────────────────────────────────────
  // CATEGORY 9 — PLANNED LIST (5)
  // ─────────────────────────────────────────────────────────────────
  {
    id: 'planned_10',
    title: 'The Planner',
    description: 'Add 10+ anime to your planned list',
    icon: '📋',
    rarity: 'common',
    category: 'Planned List',
    check: (s) => s.planned >= 10,
  },
  {
    id: 'planned_25',
    title: 'The Strategist',
    description: 'Add 25+ anime to your planned list',
    icon: '🗒️',
    rarity: 'uncommon',
    category: 'Planned List',
    check: (s) => s.planned >= 25,
  },
  {
    id: 'planned_50',
    title: 'Anime Archivist',
    description: 'Add 50+ anime to your planned list',
    icon: '📚',
    rarity: 'uncommon',
    category: 'Planned List',
    check: (s) => s.planned >= 50,
  },
  {
    id: 'planned_100',
    title: 'Grand Archivist',
    description: 'Add 100+ anime to your planned list',
    icon: '🏛️',
    rarity: 'rare',
    category: 'Planned List',
    check: (s) => s.planned >= 100,
  },
  {
    id: 'planned_250',
    title: 'Dream Library',
    description: 'Add 250+ anime to your planned list — the eternal backlog',
    icon: '🌐',
    rarity: 'epic',
    category: 'Planned List',
    check: (s) => s.planned >= 250,
  },

  // ─────────────────────────────────────────────────────────────────
  // CATEGORY 10 — DROPPED LIST (4)
  // ─────────────────────────────────────────────────────────────────
  {
    id: 'dropped_5',
    title: 'Picky Viewer',
    description: 'Drop 5 anime — quality matters to you',
    icon: '🚫',
    rarity: 'common',
    category: 'Dropped List',
    check: (s) => s.dropped >= 5,
  },
  {
    id: 'dropped_10',
    title: 'No Mercy',
    description: 'Drop 10 anime',
    icon: '❌',
    rarity: 'uncommon',
    category: 'Dropped List',
    check: (s) => s.dropped >= 10,
  },
  {
    id: 'dropped_25',
    title: 'Quality Control',
    description: 'Drop 25 anime',
    icon: '⚖️',
    rarity: 'uncommon',
    category: 'Dropped List',
    check: (s) => s.dropped >= 25,
  },
  {
    id: 'dropped_50',
    title: 'The Judge',
    description: 'Drop 50 anime — no anime is safe from your verdict',
    icon: '🔨',
    rarity: 'rare',
    category: 'Dropped List',
    check: (s) => s.dropped >= 50,
  },

  // ─────────────────────────────────────────────────────────────────
  // CATEGORY 11 — DIVERSITY & SPECIAL (7)
  // ─────────────────────────────────────────────────────────────────
  {
    id: 'genre_diversity_5',
    title: 'Genre Curious',
    description: 'Watch anime in 5 different genres',
    icon: '🌈',
    rarity: 'common',
    category: 'Diversity',
    check: (s) => s.uniqueGenresWatched >= 5,
  },
  {
    id: 'genre_diversity_10',
    title: 'Genre Explorer',
    description: 'Watch anime in 10 different genres',
    icon: '🌍',
    rarity: 'uncommon',
    category: 'Diversity',
    check: (s) => s.uniqueGenresWatched >= 10,
  },
  {
    id: 'genre_diversity_15',
    title: 'Genre Pioneer',
    description: 'Watch anime in 15 different genres',
    icon: '🌌',
    rarity: 'rare',
    category: 'Diversity',
    check: (s) => s.uniqueGenresWatched >= 15,
  },
  {
    id: 'genre_diversity_all',
    title: 'Genre Conqueror',
    description: 'Watch anime in all 19 official genres',
    icon: '🎯',
    rarity: 'epic',
    category: 'Diversity',
    check: (s) => s.uniqueGenresWatched >= 19,
  },
  {
    id: 'mal_importer',
    title: 'The Importer',
    description: 'Import your MyAnimeList list into OtakuShelf',
    icon: '📥',
    rarity: 'uncommon',
    category: 'Diversity',
    check: (s) => s.hasMalImport === true,
  },
  {
    id: 'profile_complete',
    title: 'Identity Set',
    description: 'Set your bio, username, and cover image',
    icon: '🪪',
    rarity: 'common',
    category: 'Diversity',
    check: (s) => s.hasBio && s.hasUsername && s.hasCoverImage,
  },
  {
    id: 'mean_score_high',
    title: 'Connoisseur',
    description: 'Maintain a mean score of 4.0+ across 20+ rated anime',
    icon: '🌟',
    rarity: 'rare',
    category: 'Diversity',
    check: (s) => s.ratedCount >= 20 && s.avgRating >= 4.0,
  },

  // ─────────────────────────────────────────────────────────────────
  // CATEGORY 12 — ACTIVITY & ACCOUNT AGE (7)
  // ─────────────────────────────────────────────────────────────────
  {
    id: 'veteran_30d',
    title: 'Seedling',
    description: 'Account is 30+ days old',
    icon: '🌱',
    rarity: 'common',
    category: 'Account',
    check: (s) => s.accountAgeDays >= 30,
  },
  {
    id: 'veteran_90d',
    title: 'Growing',
    description: 'Account is 90+ days old',
    icon: '🌿',
    rarity: 'common',
    category: 'Account',
    check: (s) => s.accountAgeDays >= 90,
  },
  {
    id: 'veteran_180d',
    title: 'Rooted',
    description: 'Account is 180+ days old',
    icon: '🌳',
    rarity: 'uncommon',
    category: 'Account',
    check: (s) => s.accountAgeDays >= 180,
  },
  {
    id: 'veteran_1y',
    title: 'Veteran',
    description: 'Account is 1+ year old',
    icon: '⚔️',
    rarity: 'rare',
    category: 'Account',
    check: (s) => s.accountAgeDays >= 365,
  },
  {
    id: 'veteran_2y',
    title: 'Elder',
    description: 'Account is 2+ years old',
    icon: '🏯',
    rarity: 'epic',
    category: 'Account',
    check: (s) => s.accountAgeDays >= 730,
  },
  {
    id: 'google_auth',
    title: 'Google Connected',
    description: 'Signed in with Google OAuth',
    icon: '🔗',
    rarity: 'common',
    category: 'Account',
    check: (s) => s.hasGoogleAuth,
  },
  {
    id: 'mfa_enabled_badge',
    title: 'Security Conscious',
    description: 'Enabled Two-Factor Authentication (2FA)',
    icon: '🛡️',
    rarity: 'uncommon',
    category: 'Account',
    check: (s) => s.isMfaEnabled,
  },

  // ─────────────────────────────────────────────────────────────────
  // CATEGORY 13 — COLLECTOR (5)
  // ─────────────────────────────────────────────────────────────────
  {
    id: 'collector_small',
    title: 'Small Collection',
    description: 'Have 20+ anime across all your lists',
    icon: '🗂️',
    rarity: 'common',
    category: 'Collector',
    check: (s) => s.totalAnime >= 20,
  },
  {
    id: 'collector_medium',
    title: 'Medium Collection',
    description: 'Have 75+ anime across all your lists',
    icon: '🗃️',
    rarity: 'uncommon',
    category: 'Collector',
    check: (s) => s.totalAnime >= 75,
  },
  {
    id: 'collector_large',
    title: 'Large Collection',
    description: 'Have 200+ anime across all your lists',
    icon: '🏗️',
    rarity: 'rare',
    category: 'Collector',
    check: (s) => s.totalAnime >= 200,
  },
  {
    id: 'prolific',
    title: 'Prolific Watcher',
    description: 'Have 10+ currently watching AND 10+ completed at the same time',
    icon: '🎬',
    rarity: 'rare',
    category: 'Collector',
    check: (s) => s.watching >= 10 && s.completed >= 10,
  },
  {
    id: 'all_categories_5',
    title: 'The Complete Otaku',
    description: 'Have 5+ anime in every single list category simultaneously',
    icon: '🏆',
    rarity: 'epic',
    category: 'Collector',
    check: (s) => s.watching >= 5 && s.completed >= 5 && s.planned >= 5 && s.dropped >= 5,
  },
];

export default BADGES;
